const state={token:localStorage.getItem('equilibrio_token'),me:null,data:{},page:'dashboard'};
const $=s=>document.querySelector(s); const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
async function api(url,opt={}){const r=await fetch(url,{...opt,headers:{'Content-Type':'application/json',...(opt.headers||{}),...(state.token?{Authorization:`Bearer ${state.token}`}:{})}});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Erro na operação');return j}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}
function today(){return new Date().toISOString().slice(0,10)}
function fmtDate(d){if(!d)return '—';return new Date(d+'T12:00:00').toLocaleDateString('pt-BR')}
function arr(k){return Array.isArray(state.data[k])?state.data[k]:[]}
async function save(k,v){state.data[k]=v;await api('/api/data/'+k,{method:'PUT',body:JSON.stringify(v)});render()}
async function boot(){if(!state.token){showAuth();return}try{const j=await api('/api/me');state.me=j.user;state.data=j.data||{};showApp();render()}catch{localStorage.removeItem('equilibrio_token');state.token=null;showAuth()}}
function showAuth(){$('#authView').classList.remove('hidden');$('#appView').classList.add('hidden')}
function showApp(){$('#authView').classList.add('hidden');$('#appView').classList.remove('hidden');}
function openModal(title,body,onSubmit){$('#modalRoot').innerHTML=`<div class="modal-back" id="modalBack"><div class="modal"><div class="modal-head"><h3>${title}</h3><button class="close" id="closeModal">×</button></div>${body}</div></div>`;$('#closeModal').onclick=closeModal;$('#modalBack').onclick=e=>{if(e.target.id==='modalBack')closeModal()};if(onSubmit)$('#modalForm').onsubmit=async e=>{e.preventDefault();try{await onSubmit(new FormData(e.target));closeModal();toast('Salvo com sucesso');render()}catch(err){toast(err.message)}}}
function closeModal(){$('#modalRoot').innerHTML=''}
function formModal(title,fields,submit='Salvar',values={}){return `<form id="modalForm"><div class="form-grid">${fields.map(f=>`<label class="${f.wide?'wide':''}">${f.label}<${f.type==='textarea'?'textarea':f.type==='select'?'select':'input'} ${f.type==='select'?'':`type="${f.type||'text'}"`} name="${f.name}" ${f.required?'required':''}>${f.type==='select'?f.options.map(o=>`<option ${values[f.name]===o?'selected':''}>${o}</option>`).join(''):f.type==='textarea'?esc(values[f.name]||''):''}</${f.type==='textarea'?'textarea':f.type==='select'?'select':'input'}></label>`).join('')}</div><button class="btn primary full">${submit}</button></form>`}
function profile(){const p=state.data.profile||{};return `<div class="profile-cover"><div class="avatar">${esc((p.name||state.me.name||'E')[0].toUpperCase())}</div><div><h2 style="margin:0">${esc(p.name||state.me.name)}</h2><div>${esc(p.email||state.me.email)}</div><span class="pill" style="margin-top:8px;background:rgba(255,255,255,.18);color:#fff">Perfil ${profilePercent()}% completo</span></div></div><div class="card" style="margin-top:14px"><div class="progress"><span style="width:${profilePercent()}%"></span></div><p class="muted">Quanto mais informações você fornecer, mais contexto o sistema terá para personalizar sua organização.</p></div><div class="profile-grid">${[['Nascimento','birth'],['Cidade','city'],['Estado','state'],['Telefone','phone'],['Escolaridade','education'],['Curso/área','course'],['Trabalho','work'],['Rotina','routine'],['Acorda','wake'],['Dorme','sleep'],['Objetivo principal','goal'],['Preferências','preferences'],['Dificuldades','difficulties'],['Atividades favoritas','favorites'],['Observações','observations']].map(([l,k])=>`<div class="profile-field"><small>${l}</small><strong>${esc(p[k]||'Não informado')}</strong></div>`).join('')}</div><button class="btn primary full" onclick="editProfile()">Editar meu perfil</button>`}
function profilePercent(){const p=state.data.profile||{};const keys=['name','birth','city','state','phone','education','course','work','routine','wake','sleep','goal','preferences','difficulties','favorites','observations'];return Math.round(keys.filter(k=>p[k]).length/keys.length*100)}
window.editProfile=()=>{const p=state.data.profile||{};const fields=[['name','Nome completo','text'],['birth','Data de nascimento','date'],['city','Cidade','text'],['state','Estado','text'],['phone','Telefone','tel'],['education','Escolaridade','text'],['course','Curso/área','text'],['work','Situação profissional','text'],['routine','Como é sua rotina?','text'],['wake','Horário que costuma acordar','time'],['sleep','Horário que costuma dormir','time'],['goal','Objetivo principal','text'],['preferences','Preferências de organização','text'],['difficulties','O que mais atrapalha sua rotina?','textarea'],['favorites','Atividades que você gosta','textarea'],['observations','Outras informações importantes','textarea']].map(([name,label,type])=>({name,label,type,wide:type==='textarea'}));openModal('Meu perfil',formModal('',fields,'Salvar perfil',p),async fd=>{const v={...p};fields.forEach(f=>v[f.name]=fd.get(f.name));await save('profile',v);state.me.name=v.name||state.me.name})}
function dashboard(){const tasks=arr('tasks'), studies=arr('studies'), w=arr('wellness'), habits=arr('habits');const d=today();const td=tasks.filter(x=>x.date===d), done=td.filter(x=>x.done).length, sd=studies.filter(x=>x.date===d), mins=sd.reduce((a,x)=>a+Number(x.duration||0),0), hw=w.filter(x=>x.date===d).at(-1)||{};return `<div class="page-head"><div><h2>Olá, ${esc(state.me.name.split(' ')[0])} 👋</h2><div class="muted">Aqui está um resumo do seu dia.</div></div><button class="btn primary" onclick="quickAdd()">+ Registrar</button></div><div class="cards"><div class="card stat"><div class="label">Tarefas hoje</div><div class="value">${done}/${td.length}</div></div><div class="card stat"><div class="label">Estudo hoje</div><div class="value">${mins} min</div></div><div class="card stat"><div class="label">Sono</div><div class="value">${hw.sleep||'—'} h</div></div><div class="card stat"><div class="label">Humor</div><div class="value">${hw.mood||'—'}</div></div></div><div class="two"><div class="card"><div class="page-head"><div><h3>Agenda de hoje</h3><span class="muted">${td.length} tarefas</span></div><button class="mini primary" onclick="go('planner')">Ver tudo</button></div><div class="list">${td.length?td.map(taskItem).join(''):'<div class="empty">Nenhuma tarefa para hoje.</div>'}</div></div><div class="card"><h3>Seus hábitos</h3><div class="list">${habits.slice(0,5).map(h=>`<div class="item"><div><div class="item-title">${esc(h.name)}</div><div class="item-meta">Meta: ${esc(h.target||'Diária')}</div></div><button class="mini primary" onclick="toggleHabit('${h.id}')">${h.done?'✓ Feito':'Marcar'}</button></div>`).join('')||'<div class="empty">Cadastre seus primeiros hábitos.</div>'}</div></div></div>`}
function taskItem(t){return `<div class="item"><div class="item-main"><div class="item-title">${t.done?'✓ ':''}${esc(t.title)}</div><div class="item-meta">${esc(t.time||'Sem horário')} · ${esc(t.priority||'Normal')}</div></div><div class="item-actions"><button class="mini primary" onclick="toggleTask('${t.id}')">${t.done?'Desfazer':'Concluir'}</button><button class="mini danger" onclick="removeItem('tasks','${t.id}')">×</button></div></div>`}
function planner(){const list=arr('tasks').sort((a,b)=>(a.date||'').localeCompare(b.date||''));return `<div class="page-head"><div><h2>Planner</h2><div class="muted">Organize compromissos e tarefas.</div></div><button class="btn primary" onclick="addTask()">+ Nova tarefa</button></div><div class="card"><div class="list">${list.map(taskItem).join('')||'<div class="empty">Seu planner está vazio.</div>'}</div></div>`}
window.addTask=()=>openModal('Nova tarefa',formModal('',[{name:'title',label:'Tarefa',required:true},{name:'date',label:'Data',type:'date',required:true},{name:'time',label:'Horário',type:'time'},{name:'priority',label:'Prioridade',type:'select',options:['Baixa','Normal','Alta']},{name:'category',label:'Categoria'},{name:'description',label:'Descrição',type:'textarea',wide:true}]),async fd=>{const v=arr('tasks');v.push({id:crypto.randomUUID(),title:fd.get('title'),date:fd.get('date')||today(),time:fd.get('time'),priority:fd.get('priority'),category:fd.get('category'),description:fd.get('description'),done:false});await save('tasks',v)})
window.toggleTask=async id=>{const v=arr('tasks');const x=v.find(a=>a.id===id);if(x)x.done=!x.done;await save('tasks',v)};
window.toggleHabit=async id=>{const v=arr('habits');const x=v.find(a=>a.id===id);if(x)x.done=!x.done;await save('habits',v)};
window.removeItem=async(k,id)=>{if(!confirm('Excluir este item?'))return;await save(k,arr(k).filter(x=>x.id!==id));toast('Excluído')}
function studies(){const v=arr('studies');const mins=v.reduce((a,x)=>a+Number(x.duration||0),0);return `<div class="page-head"><div><h2>Estudos</h2><div class="muted">${v.length} sessões · ${mins} minutos registrados</div></div><button class="btn primary" onclick="addStudy()">+ Adicionar</button></div><div class="card"><div class="list">${v.map(x=>`<div class="item"><div><div class="item-title">${esc(x.subject)} · ${esc(x.topic||'')}</div><div class="item-meta">${fmtDate(x.date)} · ${x.duration} min ${x.done?'· concluído':''}</div></div><div class="item-actions"><button class="mini primary" onclick="toggleStudy('${x.id}')">${x.done?'Desfazer':'Concluir'}</button><button class="mini danger" onclick="removeItem('studies','${x.id}')">×</button></div></div>`).join('')||'<div class="empty">Adicione sua primeira sessão de estudo.</div>'}</div></div>`}
window.addStudy=()=>openModal('Adicionar estudo',formModal('',[{name:'subject',label:'Matéria',required:true},{name:'topic',label:'Tema'},{name:'date',label:'Data',type:'date',required:true},{name:'duration',label:'Duração (min)',type:'number',required:true},{name:'notes',label:'Observações',type:'textarea',wide:true}]),async fd=>{const v=arr('studies');v.push({id:crypto.randomUUID(),subject:fd.get('subject'),topic:fd.get('topic'),date:fd.get('date')||today(),duration:Number(fd.get('duration')||0),notes:fd.get('notes'),done:false});await save('studies',v)})
window.toggleStudy=async id=>{const v=arr('studies');const x=v.find(a=>a.id===id);if(x)x.done=!x.done;await save('studies',v)};
function wellness(){const v=arr('wellness');return `<div class="page-head"><div><h2>Meu bem-estar</h2><div class="muted">Registre como seu dia está sendo.</div></div><button class="btn primary" onclick="addWellness()">+ Registrar hoje</button></div><div class="card"><div class="list">${v.slice().reverse().map(x=>`<div class="item"><div><div class="item-title">${fmtDate(x.date)}</div><div class="item-meta">Sono: ${x.sleep||'—'} h · Tela: ${x.screen||'—'} h · Humor: ${x.mood||'—'} · Treino: ${x.workout||'—'}</div></div><button class="mini danger" onclick="removeItem('wellness','${x.id}')">×</button></div>`).join('')||'<div class="empty">Nenhum registro ainda.</div>'}</div></div>`}
window.addWellness=()=>openModal('Registro de bem-estar',formModal('',[{name:'date',label:'Data',type:'date',required:true},{name:'sleep',label:'Horas de sono',type:'number'},{name:'sleepQuality',label:'Qualidade do sono',type:'select',options:['Não informado','Ruim','Regular','Boa','Ótima']},{name:'screen',label:'Tempo de tela (h)',type:'number'},{name:'mood',label:'Humor',type:'select',options:['Muito baixo','Baixo','Neutro','Bom','Muito bom']},{name:'workout',label:'Treino/atividade'},{name:'food',label:'Alimentação'},{name:'work',label:'Trabalho'},{name:'leisure',label:'Lazer'},{name:'note',label:'Observação',type:'textarea',wide:true}]),async fd=>{const v=arr('wellness');v.push({id:crypto.randomUUID(),date:fd.get('date')||today(),...Object.fromEntries(fd.entries())});await save('wellness',v)})
function habits(){return `<div class="page-head"><div><h2>Hábitos</h2><div class="muted">Pequenas ações que você quer manter.</div></div><button class="btn primary" onclick="addHabit()">+ Novo hábito</button></div><div class="card"><div class="list">${arr('habits').map(h=>`<div class="item"><div><div class="item-title">${esc(h.name)}</div><div class="item-meta">${esc(h.frequency||'Diário')} · ${esc(h.target||'')}</div></div><div class="item-actions"><button class="mini primary" onclick="toggleHabit('${h.id}')">${h.done?'✓ Feito':'Marcar'}</button><button class="mini danger" onclick="removeItem('habits','${h.id}')">×</button></div></div>`).join('')||'<div class="empty">Nenhum hábito cadastrado.</div>'}</div></div>`}
window.addHabit=()=>openModal('Novo hábito',formModal('',[{name:'name',label:'Nome do hábito',required:true},{name:'frequency',label:'Frequência',type:'select',options:['Diário','Dias úteis','Semanal','Personalizado']},{name:'target',label:'Meta'},{name:'description',label:'Descrição',type:'textarea',wide:true}]),async fd=>{const v=arr('habits');v.push({id:crypto.randomUUID(),name:fd.get('name'),frequency:fd.get('frequency'),target:fd.get('target'),description:fd.get('description'),done:false});await save('habits',v)})
function diary(){return `<div class="page-head"><div><h2>Diário</h2><div class="muted">Registre pensamentos, acontecimentos e aprendizados.</div></div><button class="btn primary" onclick="addNote()">+ Nova nota</button></div><div class="card"><div class="list">${arr('notes').slice().reverse().map(n=>`<div class="item"><div><div class="item-title">${esc(n.title||'Sem título')}</div><div class="item-meta">${fmtDate(n.date)} · ${esc(n.text||'').slice(0,100)}</div></div><button class="mini danger" onclick="removeItem('notes','${n.id}')">×</button></div>`).join('')||'<div class="empty">Seu diário está vazio.</div>'}</div></div>`}
window.addNote=()=>openModal('Nova nota',formModal('',[{name:'title',label:'Título'},{name:'date',label:'Data',type:'date',required:true},{name:'text',label:'Como foi seu dia?',type:'textarea',wide:true,required:true}]),async fd=>{const v=arr('notes');v.push({id:crypto.randomUUID(),title:fd.get('title'),date:fd.get('date')||today(),text:fd.get('text')});await save('notes',v)})
function appointments(){return `<div class="page-head"><div><h2>Marcar consulta</h2><div class="muted">Organize seus próximos atendimentos.</div></div><button class="btn primary" onclick="addAppointment()">+ Nova consulta</button></div><div class="card"><div class="list">${arr('appointments').map(a=>`<div class="item"><div><div class="item-title">${esc(a.professional)} · ${esc(a.specialty)}</div><div class="item-meta">${fmtDate(a.date)} às ${esc(a.time||'—')} · ${esc(a.location||'')}</div></div><button class="mini danger" onclick="removeItem('appointments','${a.id}')">×</button></div>`).join('')||'<div class="empty">Nenhuma consulta cadastrada.</div>'}</div></div>`}
window.addAppointment=()=>openModal('Marcar consulta',formModal('',[{name:'professional',label:'Profissional',required:true},{name:'specialty',label:'Especialidade',required:true},{name:'date',label:'Data',type:'date',required:true},{name:'time',label:'Horário',type:'time'},{name:'location',label:'Local'},{name:'notes',label:'Observações',type:'textarea',wide:true}]),async fd=>{const v=arr('appointments');v.push({id:crypto.randomUUID(),...Object.fromEntries(fd.entries())});await save('appointments',v)})
function generic(k,title,desc,fields){const v=arr(k);return `<div class="page-head"><div><h2>${title}</h2><div class="muted">${desc}</div></div><button class="btn primary" onclick="genericAdd('${k}')">+ Adicionar</button></div><div class="card"><div class="list">${v.map(x=>`<div class="item"><div><div class="item-title">${esc(x.title||x.name||x.category||'Registro')}</div><div class="item-meta">${esc(x.detail||x.description||x.text||'')}</div></div><button class="mini danger" onclick="removeItem('${k}','${x.id}')">×</button></div>`).join('')||'<div class="empty">Nenhum registro.</div>'}</div></div>`}
window.genericAdd=(k)=>{const config={contacts:[['name','Nome'],['relation','Relação'],['phone','Telefone']],documents:[['title','Título'],['category','Categoria'],['link','Link privado']],professional:[['name','Profissional'],['specialty','Especialidade'],['phone','Telefone']],location:[['city','Cidade'],['state','Estado'],['region','Bairro/região'],['transport','Como costuma se deslocar?']],settings:[['theme','Preferência de tema']],security:[['title','Ação'],['detail','Observação']],history:[['title','Registro'],['detail','Detalhes']]}[k]||[['title','Título'],['detail','Detalhes']];openModal('Adicionar',formModal('',config.map(([name,label])=>({name,label})), 'Salvar'),async fd=>{const v=arr(k);v.push({id:crypto.randomUUID(),...Object.fromEntries(fd.entries())});await save(k,v)})}
function reports(){const studies=arr('studies'),w=arr('wellness'),tasks=arr('tasks');const total=studies.reduce((a,x)=>a+Number(x.duration||0),0),done=tasks.filter(x=>x.done).length;return `<div class="page-head"><div><h2>Relatórios</h2><div class="muted">Visão consolidada dos seus registros.</div></div></div><div class="cards"><div class="card stat"><div class="label">Minutos estudados</div><div class="value">${total}</div></div><div class="card stat"><div class="label">Tarefas concluídas</div><div class="value">${done}</div></div><div class="card stat"><div class="label">Registros de bem-estar</div><div class="value">${w.length}</div></div><div class="card stat"><div class="label">Perfil completo</div><div class="value">${profilePercent()}%</div></div></div><div class="card" style="margin-top:16px"><h3>Resumo</h3><p class="muted">Use seus registros para perceber padrões de rotina. Esta área organiza dados e não faz diagnóstico.</p></div>`}
function assistant(){const tasks=arr('tasks').filter(x=>!x.done).length, profile=profilePercent();return `<div class="page-head"><div><h2>Assistente</h2><div class="muted">Sugestões simples baseadas no que você registrou.</div></div></div><div class="card"><h3>Seu panorama</h3><div class="list"><div class="item"><div><b>${tasks}</b> tarefas pendentes</div><span class="pill">Organização</span></div><div class="item"><div>Perfil preenchido em <b>${profile}%</b></div><span class="pill">Personalização</span></div><div class="item"><div>Você pode registrar sono, humor e tela para comparar seus dias.</div><span class="pill">Bem-estar</span></div></div></div>`}
function quickAdd(){openModal('Registro rápido',`<div class="list"><button class="btn ghost full" onclick="closeModal();addTask()">✓ Tarefa</button><button class="btn ghost full" onclick="closeModal();addStudy()">▣ Estudo</button><button class="btn ghost full" onclick="closeModal();addWellness()">♡ Bem-estar</button><button class="btn ghost full" onclick="closeModal();addNote()">✎ Diário</button></div>`)}
const pages={dashboard:['Visão geral',dashboard],planner:['Planner',planner],studies:['Estudos',studies],wellness:['Meu bem-estar',wellness],habits:['Hábitos',habits],diary:['Diário',diary],reports:['Relatórios',reports],history:['Histórico',()=>generic('history','Histórico','Seus registros organizados por atividade.')],assistant:['Assistente',assistant],appointments:['Marcar consulta',appointments],professional:['Ajuda profissional',()=>generic('professional','Ajuda profissional','Guarde contatos de profissionais e referências.')],contacts:['Emergência',()=>generic('contacts','Emergência','Contatos importantes para situações urgentes.')],documents:['Documentos',()=>generic('documents','Documentos','Organize referências e documentos importantes.')],location:['Localização',()=>generic('location','Localização','Preferências gerais de localização, sem exigir endereço exato.')],settings:['Configurações',()=>generic('settings','Configurações','Preferências do aplicativo.')],security:['Segurança',()=>generic('security','Segurança','Controles básicos da sua conta.')],profile:['Meu perfil',profile]};
function render(){if(!state.me)return;const [title,fn]=pages[state.page]||pages.dashboard;$('#pageTitle').textContent=title;$('#todayLabel').textContent=new Date().toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'long'});$('#content').innerHTML=fn();document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===state.page));document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===state.page));$('#userName').textContent=state.me.name;$('#userEmail').textContent=state.me.email;const letter=(state.me.name||'E')[0].toUpperCase();$('#avatarLetter').textContent=letter;$('#profileQuick').textContent=letter}
window.go=p=>{state.page=p;render()};
$('#nav').onclick=e=>{const b=e.target.closest('button[data-page]');if(b)go(b.dataset.page)};$('#profileNav').onclick=()=>go('profile');$('#profileQuick').onclick=()=>go('profile');$('#logoutBtn').onclick=()=>{localStorage.removeItem('equilibrio_token');state.token=null;showAuth()};$('#themeBtn').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('equilibrio_theme',document.body.classList.contains('dark')?'dark':'light')};
function initBottom(){if(document.querySelector('.bottom-nav'))return;const b=document.createElement('div');b.className='bottom-nav';b.innerHTML=[['dashboard','⌂','Início'],['planner','✓','Planner'],['studies','▣','Estudos'],['wellness','♡','Bem-estar'],['profile','●','Perfil']].map(x=>`<button data-page="${x[0]}"><b>${x[1]}</b>${x[2]}</button>`).join('');b.onclick=e=>{const x=e.target.closest('button[data-page]');if(x)go(x.dataset.page)};document.body.appendChild(b)}
function auth(){document.querySelectorAll('.auth-tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.auth-tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#loginForm').classList.toggle('hidden',b.dataset.auth!=='login');$('#registerForm').classList.toggle('hidden',b.dataset.auth!=='register')});$('#loginForm').onsubmit=async e=>{e.preventDefault();try{const j=await api('/api/auth/login',{method:'POST',body:JSON.stringify({email:$('#loginEmail').value,password:$('#loginPassword').value})});state.token=j.token;localStorage.setItem('equilibrio_token',j.token);await boot()}catch(err){toast(err.message)}};$('#registerForm').onsubmit=async e=>{e.preventDefault();try{const j=await api('/api/auth/register',{method:'POST',body:JSON.stringify({name:$('#regName').value,email:$('#regEmail').value,password:$('#regPassword').value,birth:$('#regBirth').value,city:$('#regCity').value})});state.token=j.token;localStorage.setItem('equilibrio_token',j.token);await boot()}catch(err){toast(err.message)}}}
if(localStorage.getItem('equilibrio_theme')==='dark')document.body.classList.add('dark');auth();initBottom();boot();
